# Prepare the latest x86-64-v3 libmpv development package before media_kit's
# generated CMake is loaded. media_kit expects flat headers in libmpv/include.
if(CMAKE_VERSION VERSION_LESS "3.19")
  message(FATAL_ERROR "KwokShing/mpv-winbuild resolution requires CMake 3.19 or newer.")
endif()

set(KWOKSHING_LIBMPV_DIR "${CMAKE_BINARY_DIR}/libmpv")
set(KWOKSHING_LIBMPV_STAMP "${KWOKSHING_LIBMPV_DIR}/.kwokshing-source")
set(KWOKSHING_LIBMPV_RELEASE_JSON
  "${CMAKE_BINARY_DIR}/kwokshing-mpv-winbuild-release.json")
set(KWOKSHING_LIBMPV_RELEASE_API
  "https://api.github.com/repos/KwokShing/mpv-winbuild/releases/latest")

function(kwokshing_libmpv_is_valid result)
  if(EXISTS "${KWOKSHING_LIBMPV_DIR}/include/client.h"
      AND EXISTS "${KWOKSHING_LIBMPV_DIR}/include/render.h"
      AND EXISTS "${KWOKSHING_LIBMPV_DIR}/libmpv.dll.a"
      AND EXISTS "${KWOKSHING_LIBMPV_DIR}/libmpv-2.dll"
      AND EXISTS "${KWOKSHING_LIBMPV_STAMP}")
    set(${result} TRUE PARENT_SCOPE)
  else()
    set(${result} FALSE PARENT_SCOPE)
  endif()
endfunction()

kwokshing_libmpv_is_valid(KWOKSHING_LIBMPV_CACHE_VALID)
message(STATUS "Resolving the latest KwokShing/mpv-winbuild Release ...")
file(DOWNLOAD "${KWOKSHING_LIBMPV_RELEASE_API}"
  "${KWOKSHING_LIBMPV_RELEASE_JSON}"
  HTTPHEADER "Accept: application/vnd.github+json"
  HTTPHEADER "X-GitHub-Api-Version: 2022-11-28"
  TLS_VERIFY ON
  STATUS KWOKSHING_LIBMPV_RELEASE_STATUS
  LOG KWOKSHING_LIBMPV_RELEASE_LOG)
list(GET KWOKSHING_LIBMPV_RELEASE_STATUS 0 KWOKSHING_LIBMPV_RELEASE_CODE)

if(NOT KWOKSHING_LIBMPV_RELEASE_CODE EQUAL 0)
  list(GET KWOKSHING_LIBMPV_RELEASE_STATUS 1 KWOKSHING_LIBMPV_RELEASE_MESSAGE)
  if(KWOKSHING_LIBMPV_CACHE_VALID)
    message(WARNING "Could not query KwokShing/mpv-winbuild (${KWOKSHING_LIBMPV_RELEASE_MESSAGE}); using the verified cached libmpv package.")
    return()
  endif()
  message(FATAL_ERROR "Could not query KwokShing/mpv-winbuild and no verified libmpv cache exists: ${KWOKSHING_LIBMPV_RELEASE_MESSAGE}")
endif()

file(READ "${KWOKSHING_LIBMPV_RELEASE_JSON}" KWOKSHING_LIBMPV_RELEASE_RESPONSE)
string(JSON KWOKSHING_LIBMPV_ASSET_COUNT ERROR_VARIABLE KWOKSHING_LIBMPV_JSON_ERROR
  LENGTH "${KWOKSHING_LIBMPV_RELEASE_RESPONSE}" assets)
if(NOT KWOKSHING_LIBMPV_JSON_ERROR STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Could not parse KwokShing/mpv-winbuild Release metadata: ${KWOKSHING_LIBMPV_JSON_ERROR}")
endif()

set(KWOKSHING_LIBMPV_MATCH_COUNT 0)
math(EXPR KWOKSHING_LIBMPV_LAST_ASSET "${KWOKSHING_LIBMPV_ASSET_COUNT} - 1")
if(KWOKSHING_LIBMPV_LAST_ASSET GREATER_EQUAL 0)
  foreach(KWOKSHING_LIBMPV_ASSET_INDEX RANGE ${KWOKSHING_LIBMPV_LAST_ASSET})
    string(JSON KWOKSHING_LIBMPV_CANDIDATE_NAME
      GET "${KWOKSHING_LIBMPV_RELEASE_RESPONSE}" assets
        ${KWOKSHING_LIBMPV_ASSET_INDEX} name)
    if(KWOKSHING_LIBMPV_CANDIDATE_NAME MATCHES
        "^mpv-dev-x86_64-v3-.*[.]7z$")
      math(EXPR KWOKSHING_LIBMPV_MATCH_COUNT
        "${KWOKSHING_LIBMPV_MATCH_COUNT} + 1")
      set(KWOKSHING_LIBMPV_ASSET_NAME "${KWOKSHING_LIBMPV_CANDIDATE_NAME}")
      string(JSON KWOKSHING_LIBMPV_ASSET_ID
        GET "${KWOKSHING_LIBMPV_RELEASE_RESPONSE}" assets
          ${KWOKSHING_LIBMPV_ASSET_INDEX} id)
      string(JSON KWOKSHING_LIBMPV_ASSET_URL
        GET "${KWOKSHING_LIBMPV_RELEASE_RESPONSE}" assets
          ${KWOKSHING_LIBMPV_ASSET_INDEX} browser_download_url)
      string(JSON KWOKSHING_LIBMPV_ASSET_DIGEST
        GET "${KWOKSHING_LIBMPV_RELEASE_RESPONSE}" assets
          ${KWOKSHING_LIBMPV_ASSET_INDEX} digest)
    endif()
  endforeach()
endif()

if(NOT KWOKSHING_LIBMPV_MATCH_COUNT EQUAL 1)
  message(FATAL_ERROR "Expected exactly one mpv-dev-x86_64-v3-*.7z asset in the latest KwokShing/mpv-winbuild Release; found ${KWOKSHING_LIBMPV_MATCH_COUNT}.")
endif()
if(NOT KWOKSHING_LIBMPV_ASSET_DIGEST MATCHES "^sha256:")
  message(FATAL_ERROR "The selected KwokShing/mpv-winbuild asset has no SHA-256 digest.")
endif()
string(REGEX REPLACE "^sha256:" "" KWOKSHING_LIBMPV_SHA256
  "${KWOKSHING_LIBMPV_ASSET_DIGEST}")
string(LENGTH "${KWOKSHING_LIBMPV_SHA256}" KWOKSHING_LIBMPV_SHA256_LENGTH)
if(NOT KWOKSHING_LIBMPV_SHA256_LENGTH EQUAL 64
    OR NOT KWOKSHING_LIBMPV_SHA256 MATCHES "^[0-9A-Fa-f]+$")
  message(FATAL_ERROR "The selected KwokShing/mpv-winbuild asset has an invalid SHA-256 digest.")
endif()
string(TOLOWER "${KWOKSHING_LIBMPV_SHA256}" KWOKSHING_LIBMPV_SHA256)
set(KWOKSHING_LIBMPV_EXPECTED_STAMP
  "${KWOKSHING_LIBMPV_ASSET_ID}:${KWOKSHING_LIBMPV_SHA256}")

if(KWOKSHING_LIBMPV_CACHE_VALID)
  file(READ "${KWOKSHING_LIBMPV_STAMP}" KWOKSHING_LIBMPV_CACHED_STAMP)
  string(STRIP "${KWOKSHING_LIBMPV_CACHED_STAMP}" KWOKSHING_LIBMPV_CACHED_STAMP)
  if(KWOKSHING_LIBMPV_CACHED_STAMP STREQUAL KWOKSHING_LIBMPV_EXPECTED_STAMP)
    message(STATUS "Using cached ${KWOKSHING_LIBMPV_ASSET_NAME}.")
    return()
  endif()
endif()

set(KWOKSHING_LIBMPV_ARCHIVE
  "${CMAKE_BINARY_DIR}/${KWOKSHING_LIBMPV_ASSET_NAME}")
set(KWOKSHING_LIBMPV_ARCHIVE_VALID FALSE)
if(EXISTS "${KWOKSHING_LIBMPV_ARCHIVE}")
  file(SHA256 "${KWOKSHING_LIBMPV_ARCHIVE}" KWOKSHING_LIBMPV_CACHED_SHA256)
  string(TOLOWER "${KWOKSHING_LIBMPV_CACHED_SHA256}" KWOKSHING_LIBMPV_CACHED_SHA256)
  if(KWOKSHING_LIBMPV_CACHED_SHA256 STREQUAL KWOKSHING_LIBMPV_SHA256)
    set(KWOKSHING_LIBMPV_ARCHIVE_VALID TRUE)
  else()
    file(REMOVE "${KWOKSHING_LIBMPV_ARCHIVE}")
  endif()
endif()

if(NOT KWOKSHING_LIBMPV_ARCHIVE_VALID)
  message(STATUS "Downloading ${KWOKSHING_LIBMPV_ASSET_NAME} ...")
  file(DOWNLOAD "${KWOKSHING_LIBMPV_ASSET_URL}"
    "${KWOKSHING_LIBMPV_ARCHIVE}"
    EXPECTED_HASH SHA256=${KWOKSHING_LIBMPV_SHA256}
    TLS_VERIFY ON SHOW_PROGRESS
    STATUS KWOKSHING_LIBMPV_DOWNLOAD_STATUS)
  list(GET KWOKSHING_LIBMPV_DOWNLOAD_STATUS 0 KWOKSHING_LIBMPV_DOWNLOAD_CODE)
  if(NOT KWOKSHING_LIBMPV_DOWNLOAD_CODE EQUAL 0)
    list(GET KWOKSHING_LIBMPV_DOWNLOAD_STATUS 1 KWOKSHING_LIBMPV_DOWNLOAD_MESSAGE)
    file(REMOVE "${KWOKSHING_LIBMPV_ARCHIVE}")
    message(FATAL_ERROR "Failed to download or verify ${KWOKSHING_LIBMPV_ASSET_NAME}: ${KWOKSHING_LIBMPV_DOWNLOAD_MESSAGE}")
  endif()
endif()

set(KWOKSHING_LIBMPV_STAGING "${CMAKE_BINARY_DIR}/kwokshing-libmpv-staging")
set(KWOKSHING_LIBMPV_RAW "${KWOKSHING_LIBMPV_STAGING}/raw")
set(KWOKSHING_LIBMPV_PREPARED "${KWOKSHING_LIBMPV_STAGING}/libmpv")
file(REMOVE_RECURSE "${KWOKSHING_LIBMPV_STAGING}")
file(MAKE_DIRECTORY "${KWOKSHING_LIBMPV_RAW}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E tar xf "${KWOKSHING_LIBMPV_ARCHIVE}"
  WORKING_DIRECTORY "${KWOKSHING_LIBMPV_RAW}"
  RESULT_VARIABLE KWOKSHING_LIBMPV_EXTRACT_RESULT)
if(NOT KWOKSHING_LIBMPV_EXTRACT_RESULT EQUAL 0
    OR NOT EXISTS "${KWOKSHING_LIBMPV_RAW}/include/mpv/client.h"
    OR NOT EXISTS "${KWOKSHING_LIBMPV_RAW}/include/mpv/render.h"
    OR NOT EXISTS "${KWOKSHING_LIBMPV_RAW}/libmpv.dll.a"
    OR NOT EXISTS "${KWOKSHING_LIBMPV_RAW}/libmpv-2.dll")
  file(REMOVE_RECURSE "${KWOKSHING_LIBMPV_STAGING}")
  message(FATAL_ERROR "${KWOKSHING_LIBMPV_ASSET_NAME} is not a valid libmpv development package.")
endif()

file(MAKE_DIRECTORY "${KWOKSHING_LIBMPV_PREPARED}/include")
file(COPY "${KWOKSHING_LIBMPV_RAW}/include/mpv/"
  DESTINATION "${KWOKSHING_LIBMPV_PREPARED}/include")
file(COPY
  "${KWOKSHING_LIBMPV_RAW}/libmpv.dll.a"
  "${KWOKSHING_LIBMPV_RAW}/libmpv-2.dll"
  DESTINATION "${KWOKSHING_LIBMPV_PREPARED}")
file(WRITE "${KWOKSHING_LIBMPV_PREPARED}/.kwokshing-source"
  "${KWOKSHING_LIBMPV_EXPECTED_STAMP}\n")

set(KWOKSHING_LIBMPV_BACKUP "${CMAKE_BINARY_DIR}/libmpv-backup")
file(REMOVE_RECURSE "${KWOKSHING_LIBMPV_BACKUP}")
if(EXISTS "${KWOKSHING_LIBMPV_DIR}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E rename
    "${KWOKSHING_LIBMPV_DIR}" "${KWOKSHING_LIBMPV_BACKUP}"
    RESULT_VARIABLE KWOKSHING_LIBMPV_BACKUP_RESULT)
  if(NOT KWOKSHING_LIBMPV_BACKUP_RESULT EQUAL 0)
    file(REMOVE_RECURSE "${KWOKSHING_LIBMPV_STAGING}")
    message(FATAL_ERROR "Could not replace the existing libmpv build cache.")
  endif()
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E rename
  "${KWOKSHING_LIBMPV_PREPARED}" "${KWOKSHING_LIBMPV_DIR}"
  RESULT_VARIABLE KWOKSHING_LIBMPV_ACTIVATE_RESULT)
if(NOT KWOKSHING_LIBMPV_ACTIVATE_RESULT EQUAL 0)
  if(EXISTS "${KWOKSHING_LIBMPV_BACKUP}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E rename
      "${KWOKSHING_LIBMPV_BACKUP}" "${KWOKSHING_LIBMPV_DIR}")
  endif()
  file(REMOVE_RECURSE "${KWOKSHING_LIBMPV_STAGING}")
  message(FATAL_ERROR "Could not activate ${KWOKSHING_LIBMPV_ASSET_NAME}.")
endif()
file(REMOVE_RECURSE "${KWOKSHING_LIBMPV_BACKUP}" "${KWOKSHING_LIBMPV_STAGING}")
message(STATUS "Prepared ${KWOKSHING_LIBMPV_ASSET_NAME} for media_kit.")